### ISSUE TITLE
ошибка в инструкции установки 

### ISSUE THREAD

**Issue by DjamalTea** [X88Y/mash#5]
`pip install loguru`
`Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement loguru (from versions: none)
ERROR: No matching distribution found for loguru`
c `pip3 install loguru` сработала
поменяй в инструкции

**Comment by DjamalTea** [comment]
сори увидел не твоя инструкция

**Comment by Azazel-h** [comment]
Это зависит от версии питона и пипа, на разных система по-разному вроде как + зависит от того на какой питон хочешь поставить пакет.
